#!/bin/bash

# Do not forget to select a proper partition if
# the default one is no fit for the job!

#SBATCH --output=./logs/out.%j
#SBATCH --error=./logs/err.%j
#SBATCH --nodes=1          # number of nodes
#SBATCH --ntasks=1         # number of processor cores (i.e. tasks)
#SBATCH --exclusive
#SBATCH --time=01:00:00    # walltime
#SBATCH --gres=gpu:1
#SBATCH --reservation=pram 

# Stop operation on first error.
set -e

# Load environment modules for your application here.
source /etc/profile.d/modules.sh
module purge
module load cuda/12.0

# Actual work starting here.

srun ./mm_cuBlas_float.run 2048
srun ./mm_cuBlas_float.run 2048
srun ./mm_cuBlas_float.run 8192
srun ./mm_cuBlas_float.run 8192