#!/bin/bash

# Do not forget to select a proper partition if
# the default one is no fit for the job!

#SBATCH --output=./logs/out.%j
#SBATCH --error=./logs/err.%j
#SBATCH --nodes=1          # number of nodes
#SBATCH --exclusive
#SBATCH --time=00:30:00    # walltime
#SBATCH --gres=gpu:1
#SBATCH --reservation=pram 

# Stop operation on first error.
set -e

# Load environment modules for your application here.
source /etc/profile.d/modules.sh
module purge
module load cuda/11.6

# Start your application.
echo "PCRSolve: "
srun ./pcrsolve_omp 50000000

echo ""

echo "PCRSolveGPU: "
srun ./pcrsolve_cuda 50000000

echo ""

echo "PCRSolveOMP_GPU: "
srun ./pcrsolve_omp_gpu 50000000
