#!/bin/bash

# Do not forget to select a proper partition if
# the default one is no fit for the job!

#SBATCH --output=./logs/out.%j
#SBATCH --error=./logs/err.%j
#SBATCH --nodes=1          # number of nodes
#SBATCH --exclusive
#SBATCH --time=00:30:00    # walltime
#SBATCH --gres=gpu:1
#SBATCH --reservation=pram 

# Stop operation on first error.
set -e

# Load environment modules for your application here.
source /etc/profile.d/modules.sh
module purge
module load cuda/12.0
export OMP_NUM_THREADS=24

# Start your application.
echo "PCRSolve: "
echo "5.000 equations:" 
srun --cpus-per-task=24 ./pcrsolve_omp.run 5000
srun --cpus-per-task=24 ./pcrsolve_omp.run 5000
srun --cpus-per-task=24 ./pcrsolve_omp.run 5000
srun --cpus-per-task=24 ./pcrsolve_omp.run 5000
srun --cpus-per-task=24 ./pcrsolve_omp.run 5000
echo ""
echo "500.000 equations:"
srun --cpus-per-task=24 ./pcrsolve_omp.run 500000
srun --cpus-per-task=24 ./pcrsolve_omp.run 500000
srun --cpus-per-task=24 ./pcrsolve_omp.run 500000
srun --cpus-per-task=24 ./pcrsolve_omp.run 500000
srun --cpus-per-task=24 ./pcrsolve_omp.run 500000
echo ""
echo "5.000.000 equations:"
srun --cpus-per-task=24 ./pcrsolve_omp.run 5000000
srun --cpus-per-task=24 ./pcrsolve_omp.run 5000000
srun --cpus-per-task=24 ./pcrsolve_omp.run 5000000
srun --cpus-per-task=24 ./pcrsolve_omp.run 5000000
srun --cpus-per-task=24 ./pcrsolve_omp.run 5000000
echo ""
echo "50.000.000 equations:"
srun --cpus-per-task=24 ./pcrsolve_omp.run 50000000
srun --cpus-per-task=24 ./pcrsolve_omp.run 50000000
srun --cpus-per-task=24 ./pcrsolve_omp.run 50000000
srun --cpus-per-task=24 ./pcrsolve_omp.run 50000000
srun --cpus-per-task=24 ./pcrsolve_omp.run 50000000

echo ""
echo ""

echo "PCRSolveGPU: "
echo "5.000 equations:"
srun ./pcrsolve_cuda.run 5000
srun ./pcrsolve_cuda.run 5000
srun ./pcrsolve_cuda.run 5000
srun ./pcrsolve_cuda.run 5000
srun ./pcrsolve_cuda.run 5000
echo ""
echo "500.000 equations:"
srun ./pcrsolve_cuda.run 500000
srun ./pcrsolve_cuda.run 500000
srun ./pcrsolve_cuda.run 500000
srun ./pcrsolve_cuda.run 500000
srun ./pcrsolve_cuda.run 500000
echo ""
echo "5.000.000 equations:"
srun ./pcrsolve_cuda.run 5000000
srun ./pcrsolve_cuda.run 5000000
srun ./pcrsolve_cuda.run 5000000
srun ./pcrsolve_cuda.run 5000000
srun ./pcrsolve_cuda.run 5000000
echo ""
echo "50.000.000 equations:"
srun ./pcrsolve_cuda.run 50000000
srun ./pcrsolve_cuda.run 50000000
srun ./pcrsolve_cuda.run 50000000
srun ./pcrsolve_cuda.run 50000000
srun ./pcrsolve_cuda.run 50000000

echo ""
echo ""

export OMP_NUM_THREADS=1
echo "PCRSolveOMP_GPU: "
echo "5.000 equations:"
srun ./pcrsolve_omp_gpu.run 5000
srun ./pcrsolve_omp_gpu.run 5000
srun ./pcrsolve_omp_gpu.run 5000
srun ./pcrsolve_omp_gpu.run 5000
srun ./pcrsolve_omp_gpu.run 5000
echo ""
echo "500.000 equations:"
srun ./pcrsolve_omp_gpu.run 500000
srun ./pcrsolve_omp_gpu.run 500000
srun ./pcrsolve_omp_gpu.run 500000
srun ./pcrsolve_omp_gpu.run 500000
srun ./pcrsolve_omp_gpu.run 500000
echo ""
echo "5.000.000 equations:"
srun ./pcrsolve_omp_gpu.run 5000000
srun ./pcrsolve_omp_gpu.run 5000000
srun ./pcrsolve_omp_gpu.run 5000000
srun ./pcrsolve_omp_gpu.run 5000000
srun ./pcrsolve_omp_gpu.run 5000000
echo ""
echo "50.000.000 equations:"
srun ./pcrsolve_omp_gpu.run 50000000
srun ./pcrsolve_omp_gpu.run 50000000
srun ./pcrsolve_omp_gpu.run 50000000
srun ./pcrsolve_omp_gpu.run 50000000
srun ./pcrsolve_omp_gpu.run 50000000
