#!/bin/bash

# Do not forget to select a proper partition if
# the default one is no fit for the job!

#SBATCH --output=./logs/out.%j
#SBATCH --error=./logs/err.%j
#SBATCH --nodes=1          # number of nodes
#SBATCH --exclusive
#SBATCH --time=00:30:00    # walltime
#SBATCH --gres=gpu:1
#SBATCH --reservation=pram 

# Stop operation on first error.
set -e

# Load environment modules for your application here.
source /etc/profile.d/modules.sh
module purge
module load cuda/12.0
export OMP_NUM_THREADS=1

# Start your application.
echo "start cuda"
srun ./pcrsolve_cuda.run 50000000
echo "start omp gpu"
srun ./pcrsolve_omp_gpu.run 50000000
export OMP_NUM_THREADS=24
echo "start omp"
srun --cpus-per-task=24 ./pcrsolve_omp.run 50000000
# srun nsys profile -f true -o test_simd_inline -t cuda,openmp,nvtx --stats=true ./pcrsolve_omp_gpu.run 50000000
# srun nsys profile -f true -o cuda_restricted -t cuda,osrt,nvtx --stats=true ./pcrsolve_cuda_nsys.run 50000000